pref("extensions.shortly.contextmenu.enable", true);
pref("extensions.shortly.urlbox.enable", true);
pref("extensions.shortly.addonbar.enable", true);
pref("extensions.shortly.accesskey.enable", true);
pref("extensions.shortly.accesskey.combination", "CTRL-ALT-I");
pref("extensions.shortly.clipboard.enable", true);
pref("extensions.shortly.key", "b48b63d7123ea5fe4d07c99d1f66562fef73413b");
pref("extensions.shortly.key.override", "");
pref("extensions.shortly.key.expiry", "0");